services:
  backend:
    build: ./backend
    container_name: nest-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - raito
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: comments_db
      RAITO_HOST: raito
      RAITO_PORT: 9110

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comments_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  raito:
    image: stbestich/raito-cache:latest_amd64
    container_name: raito
    ports:
      - "9110:9110"
    environment:
      NODE_ENV: production
      PORT: 9110
      HOST: 0.0.0.0
    tty: true
    stdin_open: true

volumes:
  pgdata:
