export enum EnvEnum {
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  RAITO_HOST = 'RAITO_HOST',
  RAITO_PORT = 'RAITO_PORT',
  JWT_SECRET = 'JWT_SECRET',
}
